s1={1,2,3,4,5}
s2={4,5,6,7,8}
s3={4,5,10,11,1}
print('s1',s1)
print('s2',s2)
union=s1.union(s2,s3)
print('union',union)
intersection=s1.intersection(s2)
print('intersection',intersection)
difference=s1.difference(s2)
print('difference',difference)
difference=s2.difference(s1)
print('difference',difference)
symmetric_difference=s1.symmetric_difference(s2)
print('symmetric_difference',symmetric_difference)
